name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 13 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: james.a.eddy@gmail.com
        heroku_app_name: jeffcupdb-heroku

